language: cpp
compiler: gcc

before_install:
  - ./projects/install-premake5.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - zlib1g-dev
    - minizip-dev

script:
  - premake-5.0.0-alpha6/bin/release/premake5 gmake
  - cd build
  - make

