language: cpp
compiler: gcc
sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - zlib1g-dev
    - libsdl1.2-dev
    - libssl-dev
    - libglew-dev
    - libfreetype6-dev
    - libunittest++-dev

before_install:
  - ./projects/install-libzip.sh
  - ./projects/install-premake5.sh
  - ./projects/install-box2d.sh
  - export CXX="g++-5" CC="gcc-5"

script:
  - premake-core/bin/release/premake5 --travis --with-libzip=../libzip-1.0.1 --with-box2d=../Box2D-master gmake
  - cd build
  - make
  - cd ../bin && LD_LIBRARY_PATH=. ./UnitTestd

