
#include <stdio.h>

#include "astcontents.h"

#include "codestream.h"
#include "codeblock.h"

// bison : bison -d language.bison -o language.c
// flex  : flex -I language.flex

extern FILE* yyin;

extern int yyparse();

extern ASTContents* pcontents;

int main(int argc, char *argv[])
{
   yyin = fopen("game.cpp", "r");
   yyparse();
   fclose(yyin);

   if ( pcontents != 0 )
   {
      pcontents->prettyPrint();

      bool valid = pcontents->validate();
      if ( valid )
         cout << "Valid contents" << endl;

      CodeStream stream("output.cpp");
      stream << "/* Script registration auto-generated by cpp2lua */" << CodeStream::endl;
      stream << "#include \"scriptlib.h\"" << CodeStream::endl;
      stream << "#include \"scriptclass.h\"" << CodeStream::endl;

      pcontents->generateCode(stream, ASTNode::eFirstPhase);

      stream << "void register(ScriptLib& scriptlib)" << CodeStream::endl << "{" << CodeStream::endl;
      {
         CodeBlock block;
         pcontents->generateCode(stream, ASTNode::eSecondPhase);
      }
      stream << "}" << CodeStream::endl;

      delete pcontents;
   }
   else
   {
      cout << "An error occured, can not proceed." << endl;
   }

   return 0;
}
