
#include <stdio.h>
#include "astcontents.h"

// bison : bison -d language.bison -o language.c
// flex  : flex -I language.flex

extern FILE* yyin;

extern int yyparse();

extern ASTContents* pcontents;

int main(int argc, char *argv[])
{
   yyin = fopen("example.cpp", "r");
   yyparse();
   fclose(yyin);

   if ( pcontents != 0 )
   {
      pcontents->prettyPrint();

      bool valid = pcontents->validate();
      if ( valid )
         cout << "Valid contents" << endl;

      FILE* out = fopen("output.cpp", "w");

      fprintf(out, "/* Script registration auto-generated by cpp2lua */\n");
      fprintf(out, "#include \"scriptlib.h\"\n");
      fprintf(out, "#include \"scriptclass.h\"\n");

      pcontents->generateCode(out, ASTNode::eFirst);

      fprintf(out, "void register(ScriptLib& scriptlib)\n{\n");
      pcontents->generateCode(out, ASTNode::eSecond);
      fprintf(out, "}\n");

      fclose(out);

      delete pcontents;
   }
   else
   {
      cout << "An error occured, can not proceed." << endl;
   }

   return 0;
}
